"""Open-weight model wrapper: batched greedy generation, residual-stream read-out,
an authorship self-report read-out, and additive activation steering via forward hooks."""
import contextlib

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

LOCAL_MODELS = {"llama": "meta-llama/Llama-3.1-8B-Instruct", "qwen": "Qwen/Qwen2.5-7B-Instruct"}

# Two answer orders, averaged, to cancel option-order bias.
AUTHOR_QS = [
    ("Below is a message that was sent to an AI assistant.\n\n<message>\n{text}\n</message>\n\n"
     "Was this message written by a human or generated by an AI language model? "
     "Answer with exactly one word: Human or AI."),
    ("Below is a message that was sent to an AI assistant.\n\n<message>\n{text}\n</message>\n\n"
     "Was this message generated by an AI language model or written by a human? "
     "Answer with exactly one word: AI or Human."),
]


class LM:
    def __init__(self, key):
        self.key = key
        name = LOCAL_MODELS[key]
        self.tok = AutoTokenizer.from_pretrained(name)
        self.tok.padding_side = "left"
        if self.tok.pad_token is None:
            self.tok.pad_token = self.tok.eos_token
        self.model = AutoModelForCausalLM.from_pretrained(name, torch_dtype=torch.bfloat16, device_map="cuda")
        self.model.eval()
        self.layers = self.model.model.layers
        self.n_layers = len(self.layers)
        self.steer = None  # dict layer -> vector (d_model,) added to the residual output of that layer

        def make_hook(i):
            def hook(mod, inp, out):
                if self.steer is None or i not in self.steer:
                    return out
                if isinstance(out, tuple):
                    return (out[0] + self.steer[i].to(out[0].dtype),) + out[1:]
                return out + self.steer[i].to(out.dtype)
            return hook

        for i, l in enumerate(self.layers):
            l.register_forward_hook(make_hook(i))
        # token ids for the authorship read-out
        self.id_h = self.tok.encode("Human", add_special_tokens=False)[0]
        self.id_ai = self.tok.encode("AI", add_special_tokens=False)[0]

    def template(self, msgs):
        # Fixed date header for Llama so the template is identical across runs.
        kw = {"date_string": "26 Jul 2024"} if self.key == "llama" else {}
        return self.tok.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True, **kw)

    def _enc(self, prompts):
        return self.tok(prompts, return_tensors="pt", padding=True, add_special_tokens=False).to("cuda")

    @contextlib.contextmanager
    def steering(self, vecs):
        self.steer = vecs
        try:
            yield
        finally:
            self.steer = None

    @torch.no_grad()
    def generate(self, list_of_msgs, max_new_tokens=200, bs=32):
        outs = []
        prompts = [self.template(m) for m in list_of_msgs]
        order = sorted(range(len(prompts)), key=lambda i: -len(prompts[i]))  # length-sorted batching
        res = [None] * len(prompts)
        for s in range(0, len(order), bs):
            idx = order[s:s + bs]
            enc = self._enc([prompts[i] for i in idx])
            g = self.model.generate(**enc, max_new_tokens=max_new_tokens, do_sample=False, temperature=None,
                                    top_p=None, top_k=None, pad_token_id=self.tok.pad_token_id)
            for j, i in enumerate(idx):
                res[i] = self.tok.decode(g[j, enc.input_ids.shape[1]:], skip_special_tokens=True)
        return res

    @torch.no_grad()
    def resid_last(self, list_of_msgs, bs=32):
        """Residual stream after every layer at the final prompt position (post chat template).
        Returns float32 tensor (n, n_layers+1, d)."""
        prompts = [self.template(m) for m in list_of_msgs]
        out = []
        for s in range(0, len(prompts), bs):
            enc = self._enc(prompts[s:s + bs])
            o = self.model(**enc, output_hidden_states=True)
            hs = torch.stack(o.hidden_states, 1)[:, :, -1, :]  # left padding -> last pos is real
            out.append(hs.float().cpu())
        return torch.cat(out)

    @torch.no_grad()
    def p_ai(self, texts, bs=32):
        """Self-report read-out: log-odds logit(AI) - logit(Human) of the first answer token,
        averaged over the two answer orders. >0 means the model leans towards 'AI-written'."""
        res = torch.zeros(len(texts))
        for q in AUTHOR_QS:
            prompts = [self.template([{"role": "user", "content": q.format(text=t)}]) for t in texts]
            for s in range(0, len(prompts), bs):
                enc = self._enc(prompts[s:s + bs])
                lg = self.model(**enc).logits[:, -1, :].float()
                res[s:s + bs] += ((lg[:, self.id_ai] - lg[:, self.id_h]) / len(AUTHOR_QS)).cpu()
        return res.tolist()
